#!/usr/bin/env node

const cp = require('child_process');

cp.exec('git diff --staged --name-only HEAD', (err, stdout) => {
    if (err) {
        process.exit(1);
        return;
    }

    let jsFiles = stdout.toString().split('\n').filter(item => (/\.js$/).test(item));
    let mdFiles = stdout.toString().split('\n').filter(item => (/\.md$/).test(item));

    _eslint(jsFiles, err => {
        if (err) {
            process.exit(1);
            return;
        }

        _mdFormat(mdFiles, err => {
            if (err) {
                process.exit(1);
                return;
            }

            process.exit(0);
        });
    });
});

function _eslint(files, callback) {
    if (!files || files.length === 0) {
        callback(null);
        return;
    }

    cp.exec('eslint ' + files.join(' '), (err, stdout) => {
        if (err) {
            console.log(stdout.toString());
            callback(err);
            return;
        }

        callback(null);
    });
}

function _mdFormat(files, callback) {
    if (!files || files.length === 0) {
        callback(null);
        return;
    }
}
